apiVersion: v1
kind: Service
metadata:
  name: {{ include "opa.fullname" . }}
  labels:
    {{- include "opa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "opa.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: api
    - name: ingest
      port: {{ .Values.service.ingestPort }}
      targetPort: ingest
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
    - name: ws
      port: {{ .Values.service.wsPort }}
      targetPort: ws
